services:
  flash-findr-cpu:
    profiles: [ "cpu" ]
    build: ./backend
    ports:
      - "8008:8008"
    volumes:
      - ./backend/cache:/app/cache
      - ./backend/models:/app/models
    command: sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8008"
  flash-findr-gpu:
    profiles: [ "gpu" ]
    build: ./backend
    ports:
      - "8008:8008"
    volumes:
      - ./backend/cache:/app/cache
      - ./backend/models:/app/models
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    command: sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8008"
