ov_detection:
  model: "yoloe-11s-seg.pt" # Model arch / ckpt path
  device: "cpu"              # Device to run inference on
  confidence_threshold: 0.25 # Confidence threshold for detections
  iou_threshold: 0.45        # IoU threshold for NMS